version: '2'

services:
        nginx:
                image: nginx
                restart: always
                ports:
                        - "80:80"
                volumes:
                        - ./nginx/conf.d:/etc/nginx/conf.d
                links:
                        - ducatus-blockchain-api

        ducatus-blockchain-api:
                image: ducatus-blockchain-explorer-p90x
                restart: always
                volumes:
                        - blockchain-api-volume:/root/ducatusnode/data
                        - ./ducatuscoin.conf:/root/.ducatuscoin/ducatuscoin.conf
                ports:
                        - "3001:3001"
                        - "9690:9690"
                        - "9691:9691"

volumes:
        blockchain-api-volume:
